Algoritmo "Soma"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Pega dois valores, soma e exibe
// Autor(a)    : Carlos Gabriel
// Data atual  : 16/03/2022
Var
// Seção de Declarações das variáveis 
n1: inteiro
n2: inteiro
resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(n1)
escreva("Digite outro número: ")
leia(n2)
resultado <- n1 + n2
escreva("Resultado: ", resultado)

Fimalgoritmo