Algoritmo "Exercício 57"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Imprimir, em ordem crescente, os números de 1 a 10, usando
//               estrutura PARA e CONTADOR.
// Autor(a)    : Carlos Gabriel
// Data atual  : 27/03/2022
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para numero de 1 ate 10 faca
      escreval(numero)
   fimpara

Fimalgoritmo