Algoritmo "Exercício 51"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Imprimir, em ordem decrescente, os números de 1 a 10.
// Autor(a)    : Carlos Gabriel
// Data atual  : 25/03/2022
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   numero <- 11
   repita
      numero <- numero - 1
      escreval(numero)
   ate (numero = 1)

Fimalgoritmo